package main

import (
	"context"
	"fmt"
	"net"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/jingkaihe/kodelet/pkg/llm"
	"github.com/jingkaihe/kodelet/pkg/logger"
	"github.com/jingkaihe/kodelet/pkg/presenter"
	llmtypes "github.com/jingkaihe/kodelet/pkg/types/llm"
	"github.com/jingkaihe/kodelet/pkg/webui"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
)

type ServeConfig struct {
	Host         string
	Port         int
	CWD          string
	CompactRatio float64
	AuthToken    string
	SkipAuth     bool
	CORSOrigins  []string
	ConfigError  error
}

func NewServeConfig() *ServeConfig {
	return &ServeConfig{
		Host:         "localhost",
		Port:         8080,
		CWD:          "",
		CompactRatio: llmtypes.DefaultCompactRatio,
	}
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the web UI server for chatting with kodelet",
	Long: `Start a local web server that provides an interactive chat interface for kodelet.
The web UI lets you continue conversations, inspect tool activity, and browse recent
chat history from the browser while still using the same embedded assets in the binary.

The server will be available at http://localhost:8080 by default. A random
authentication token is generated unless --auth-token is provided or --skip-auth
is set.`,
	Run: func(cmd *cobra.Command, _ []string) {
		ctx := cmd.Context()
		config := getServeConfigFromFlags(cmd)
		runServeCommand(ctx, config)
	},
}

func init() {
	defaults := NewServeConfig()
	serveCmd.Flags().String("host", defaults.Host, "Host to bind the web server to")
	serveCmd.Flags().Int("port", defaults.Port, "Port to bind the web server to")
	serveCmd.Flags().String("cwd", defaults.CWD, "Default working directory for new web conversations")
	serveCmd.Flags().String("auth-token", defaults.AuthToken, "Token required to access the web UI; generated by default")
	serveCmd.Flags().Bool("skip-auth", defaults.SkipAuth, "Disable web UI token authentication")
	serveCmd.Flags().StringSlice("cors-origins", defaults.CORSOrigins, "Additional allowed CORS origins for browser clients (comma-separated or repeated); loopback origins are always allowed")
}

func getServeConfigFromFlags(cmd *cobra.Command) *ServeConfig {
	config := NewServeConfig()

	if host, err := cmd.Flags().GetString("host"); err == nil {
		config.Host = host
	}
	if port, err := cmd.Flags().GetInt("port"); err == nil {
		config.Port = port
	}
	if cwd, err := cmd.Flags().GetString("cwd"); err == nil {
		config.CWD = strings.TrimSpace(cwd)
	}
	if authToken, err := cmd.Flags().GetString("auth-token"); err == nil {
		config.AuthToken = authToken
	}
	if skipAuth, err := cmd.Flags().GetBool("skip-auth"); err == nil {
		config.SkipAuth = skipAuth
	}
	if corsOrigins, err := cmd.Flags().GetStringSlice("cors-origins"); err == nil {
		config.CORSOrigins = corsOrigins
	}
	llmConfig, err := llm.GetConfigFromViperWithCmd(cmd)
	if err != nil {
		config.ConfigError = err
	} else {
		config.CompactRatio = llmConfig.CompactRatio
	}

	return config
}

func validateServeConfig(config *ServeConfig) error {
	if config.ConfigError != nil {
		return config.ConfigError
	}

	if config.Host == "" {
		return errors.New("host cannot be empty")
	}

	if config.Host != "localhost" && config.Host != "0.0.0.0" {
		if ip := net.ParseIP(config.Host); ip == nil {
			if strings.Contains(config.Host, " ") || strings.Contains(config.Host, ":") {
				return fmt.Errorf("invalid host: %s", config.Host)
			}
		}
	}

	if config.Port < 1 || config.Port > 65535 {
		return fmt.Errorf("port must be between 1 and 65535, got %d", config.Port)
	}

	if config.Port < 1024 {
		logger.G(context.Background()).WithField("port", config.Port).Warn("using privileged port (< 1024) may require elevated permissions")
	}

	if config.CompactRatio <= 0.0 || config.CompactRatio > 1.0 {
		return errors.New("compact-ratio must be greater than 0.0 and less than or equal to 1.0")
	}

	if config.SkipAuth && config.AuthToken != "" {
		return errors.New("--auth-token cannot be used with --skip-auth")
	}

	if err := webui.ValidateAuthToken(config.AuthToken); err != nil {
		return err
	}

	if err := webui.ValidateCORSOrigins(config.CORSOrigins); err != nil {
		return err
	}

	return nil
}

func runServeCommand(ctx context.Context, config *ServeConfig) {
	if err := validateServeConfig(config); err != nil {
		presenter.Error(err, "invalid server configuration")
		os.Exit(1)
	}

	authToken := strings.TrimSpace(config.AuthToken)
	if !config.SkipAuth && authToken == "" {
		var err error
		authToken, err = webui.NewAuthToken()
		if err != nil {
			presenter.Error(err, "failed to generate auth token")
			os.Exit(1)
		}
	}

	logger.G(ctx).WithFields(map[string]any{
		"host": config.Host,
		"port": config.Port,
		"auth": !config.SkipAuth,
	}).Info("Starting web UI server")

	serverConfig := &webui.ServerConfig{
		Host:         config.Host,
		Port:         config.Port,
		CWD:          config.CWD,
		CompactRatio: config.CompactRatio,
		AuthToken:    authToken,
		CORSOrigins:  config.CORSOrigins,
	}

	server, err := webui.NewServer(ctx, serverConfig)
	if err != nil {
		presenter.Error(err, "failed to create web server")
		os.Exit(1)
	}
	defer func() {
		if closeErr := server.Close(); closeErr != nil {
			logger.G(ctx).WithError(closeErr).Error("failed to close web server")
		}
	}()

	ctx, cancel := signal.NotifyContext(ctx, os.Interrupt, syscall.SIGTERM)
	defer cancel()

	baseURL := serveBaseURL(config.Host, config.Port)
	presenter.Success(fmt.Sprintf("Web UI server starting on %s", baseURL))
	if authToken != "" {
		presenter.Info(fmt.Sprintf("Authentication token: %s", authToken))
		presenter.Info(fmt.Sprintf("Open this URL: %s", serveURLWithToken(baseURL, authToken)))
	} else {
		presenter.Warning("Web UI authentication disabled (--skip-auth)")
	}
	presenter.Info("Press Ctrl+C to stop the server")

	if err := server.Start(ctx); err != nil {
		logger.G(ctx).WithError(err).Error("web server error")
		presenter.Error(err, "web server failed")
		os.Exit(1)
	}

	presenter.Info("Web server stopped")
}

func serveBaseURL(host string, port int) string {
	displayHost := host
	if displayHost == "" {
		displayHost = "localhost"
	}
	if displayHost == "0.0.0.0" || displayHost == "::" {
		displayHost = "localhost"
	}
	if strings.Contains(displayHost, ":") && !strings.HasPrefix(displayHost, "[") {
		displayHost = "[" + displayHost + "]"
	}

	return fmt.Sprintf("http://%s:%d", displayHost, port)
}

func serveURLWithToken(baseURL string, authToken string) string {
	parsedURL, err := url.Parse(baseURL)
	if err != nil {
		return baseURL
	}

	query := parsedURL.Query()
	query.Set("token", authToken)
	parsedURL.RawQuery = query.Encode()
	return parsedURL.String()
}
