/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  // Prose mentioning modal dialogs and JS .join() calls are not DaisyUI components.
  // Their unused :has() rules make Chromium rescan long transcripts on textarea edits.
  blocklist: ['modal', 'join'],
  theme: {
    extend: {
      fontFamily: {
        'heading': ['IBM Plex Sans', 'Helvetica Neue', 'sans-serif'],
        'body': ['Crimson Pro', 'Georgia', 'serif'],
        'mono': ['JetBrains Mono', 'SFMono-Regular', 'Consolas', 'monospace'],
      },
      colors: {
        // RGB channels preserve Tailwind's /opacity modifiers in every palette.
        'kodelet': {
          'dark': 'rgb(var(--kodelet-dark-rgb) / <alpha-value>)',
          'light': 'rgb(var(--kodelet-light-rgb) / <alpha-value>)',
          'mid-gray': 'rgb(var(--kodelet-mid-gray-rgb) / <alpha-value>)',
          'light-gray': 'rgb(var(--kodelet-light-gray-rgb) / <alpha-value>)',
          'orange': 'rgb(var(--kodelet-orange-rgb) / <alpha-value>)',
          'blue': 'rgb(var(--kodelet-blue-rgb) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        kodelet: {
          'color-scheme': 'light',
          'primary': '#d97757',
          'secondary': '#6a9bcc',
          'accent': '#788c5d',
          'neutral': '#3c3836',
          'base-100': '#faf8ef',
          'base-200': '#f8f5e9',
          'base-300': '#ebdbb2',
          'base-content': '#3c3836',
          'info': '#6a9bcc',
          'success': '#788c5d',
          'warning': '#d97757',
          'error': '#d97757',
        },
        'kodelet-classic': {
          'color-scheme': 'light',
          'primary': '#d97757',
          'secondary': '#6a9bcc',
          'accent': '#788c5d',
          'neutral': '#141413',
          'base-100': '#faf9f5',
          'base-200': '#f4efe5',
          'base-300': '#e8e6dc',
          'base-content': '#141413',
          'info': '#6a9bcc',
          'success': '#788c5d',
          'warning': '#d97757',
          'error': '#d97757',
        },
        'gruvbox-dark': {
          'color-scheme': 'dark',
          'primary': '#fe8019',
          'primary-content': '#282828',
          'secondary': '#83a598',
          'secondary-content': '#282828',
          'accent': '#b8bb26',
          'accent-content': '#282828',
          'neutral': '#504945',
          'neutral-content': '#ebdbb2',
          'base-100': '#282828',
          'base-200': '#252525',
          'base-300': '#504945',
          'base-content': '#ebdbb2',
          'info': '#83a598',
          'info-content': '#282828',
          'success': '#b8bb26',
          'success-content': '#282828',
          'warning': '#fabd2f',
          'warning-content': '#282828',
          'error': '#fb7160',
          'error-content': '#282828',
        },
      },
    ],
    base: true,
    styled: true,
    utils: true,
  },
};
