name: Background Kodelet

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

env:
  TIMEOUT_MINUTES: "300"

jobs:
  background-kodelet:
    runs-on: kodelet-runner
    permissions:
      id-token: write
      issues: read
      pull-requests: read
      contents: read
    timeout-minutes: 360  # 6 hours
    if: |
      (
        (github.event_name == 'issues' && contains(github.event.issue.body, '@kodelet')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@kodelet')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@kodelet'))
      ) &&
      (
        (github.event.issue.author_association == 'OWNER' || github.event.issue.author_association == 'MEMBER' || github.event.issue.author_association == 'COLLABORATOR') ||
        (github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'COLLABORATOR') ||
        (github.event.review.author_association == 'OWNER' || github.event.review.author_association == 'MEMBER' || github.event.review.author_association == 'COLLABORATOR')
      )

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          experimental: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Kodelet
        uses: jingkaihe/kodelet-action@v0.1.8-alpha
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          kodelet-config: |
            model: "claude-sonnet-4-20250514"
            weak_model: "claude-3-5-haiku-20241022"
            max_tokens: 16000
            weak_model_max_tokens: 8192
            thinking_budget_tokens: 8000
            mcp:
              servers:
                github:
                  command: "docker"
                  args:
                    - run
                    - -i
                    - --rm
                    - -e
                    - GITHUB_PERSONAL_ACCESS_TOKEN
                    - -e
                    - GITHUB_TOOLSETS
                    - ghcr.io/github/github-mcp-server
                  envs:
                    GITHUB_TOOLSETS: "issues,pull_requests"
                    GITHUB_PERSONAL_ACCESS_TOKEN: $GITHUB_TOKEN
                  tool_white_list:
                    - get_issue
                    - get_issue_comments
                    - add_issue_comment
                    - create_pull_request
                    - create_pending_pull_request_review
                    - add_pull_request_review_comment_to_pending_review
                    - submit_pending_pull_request_review
                    - get_pull_request_diff
