name: Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release-binaries:
    name: Release Go Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Build all binaries
        run: make cross-build

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/kodelet-linux-amd64
            ./bin/kodelet-linux-arm64
            ./bin/kodelet-darwin-amd64
            ./bin/kodelet-darwin-arm64
            ./bin/kodelet-windows-amd64.exe
