name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: kodelet-runner
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version detection

      - name: Install mise
        run: |
          curl https://mise.jdx.dev/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install tools and dependencies
        run: |
          mise install
          mise run install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create GitHub Release
        run: mise run github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
