name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: kodelet-runner
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version detection

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create GitHub Release
        run: make github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
