name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: kodelet-runner
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper version detection

      - name: Install make and GitHub CLI
        run: |
          # Add GitHub CLI repository
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

          # Update package list and install both tools
          sudo apt-get update
          sudo apt-get install -y make gh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create GitHub Release
        run: make github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
